CREATE TABLE `magic_link_tokens` (
	`id` varchar(36) NOT NULL,
	`email` varchar(255) NOT NULL,
	`token` varchar(255) NOT NULL,
	`expires` datetime NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `magic_link_tokens_id` PRIMARY KEY(`id`),
	CONSTRAINT `magic_link_tokens_token_unique` UNIQUE(`token`),
	CONSTRAINT `magic_link_token_idx` UNIQUE(`token`)
);
--> statement-breakpoint
ALTER TABLE `audit_logs` MODIFY COLUMN `audit_action` enum('LOGIN_SUCCESS','LOGIN_FAILED','LOGOUT','PASSWORD_RESET_REQUESTED','PASSWORD_RESET_COMPLETED','EMAIL_VERIFIED','EMAIL_VERIFICATION_RESENT','TWO_FACTOR_ENABLED','TWO_FACTOR_DISABLED','TWO_FACTOR_VERIFIED','BACKUP_CODES_GENERATED','BACKUP_CODE_USED','SESSION_REVOKED','DEVICE_TRUSTED','SUSPICIOUS_LOGIN_DETECTED','ACCOUNT_LOCKED','ACCOUNT_UNLOCKED','ACCOUNT_BLOCKED','ACCOUNT_UNBLOCKED','ACCOUNT_DELETED','ACCOUNT_REACTIVATED','ACCOUNT_ANONYMIZED','REGISTRATION','EMAIL_CHANGE_REQUESTED','EMAIL_CHANGED','OAUTH_ACCOUNT_LINKED','OAUTH_ACCOUNT_UNLINKED','OAUTH_LOGIN','MAGIC_LINK_SENT','MAGIC_LINK_LOGIN') NOT NULL;--> statement-breakpoint
CREATE INDEX `magic_link_email_idx` ON `magic_link_tokens` (`email`);